{% set name = "FuncDesigner" %}
{% set version = "0.5629" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 2836eeaf11085dc50d49fa4fe28993a7f6e3ef0e630684d7643267311ca48e85
  patches:
    - setup.py.patch

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - scipy

test:
  imports:
    - FuncDesigner

about:
  home: http://openopt.org
  license:  BSD
  license_family: BSD
  summary: 'A python module for function design and automatic derivatives'

extra:
  recipe-maintainers:
    - AntoineD
