{% set name = "openopt" %}
{% set version = "0.5629" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 2c6901a22493053c74080c4eb66ccc46afdbf5b7cf056e3a0334b9bc88ce856a
  patches:
    - setup.py.patch

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - numpy
    - setproctitle
    - sortedcontainers

test:
  imports:
    - openopt

about:
  home: http://openopt.org
  license:  BSD
  license_family: BSD
  summary: 'A python module for numerical optimization'

extra:
  recipe-maintainers:
    - AntoineD
